[package]
name = "tendermock"
version = "0.1.0"
authors = ["CharlyCst <castes.ch@gmail.com>"]
edition = "2018"

[[bin]]
name = "tendermock"
path = "src/main.rs"

[dependencies]
jsonrpc-core = "15.0"
jsonrpc-http-server = "15.0"
jsonrpc-derive = "15.0"
prost-types = "0.6.1"


ibc = { git = "https://github.com/informalsystems/ibc-rs" }

# TODO: import this properly
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", tag = "v0.17.0-rc1"  }
tendermint-testgen = { git = "https://github.com/informalsystems/tendermint-rs", tag = "v0.17.0-rc1" }
tendermint-rpc = { git  = "https://github.com/informalsystems/tendermint-rs", tag = "v0.17.0-rc1" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", tag = "v0.17.0-rc1" }

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = [ "suggestions", "derive", "std" ]
